# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables
pipelines:
  default:
    - step:
        name: ECR Release
        image: python:3-alpine
        script:
            - pip3 install awscli
            - aws --version
            - export AWS_ACCESS_KEY_ID=$AWS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET AWS_DEFAULT_REGION=ap-southeast-1
            - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 273261189387.dkr.ecr.ap-southeast-1.amazonaws.com
            - docker build -t 273261189387.dkr.ecr.ap-southeast-1.amazonaws.com/wp-test:$BITBUCKET_BRANCH .
            - docker push 273261189387.dkr.ecr.ap-southeast-1.amazonaws.com/wp-test:$BITBUCKET_BRANCH
        services:
            - docker
        caches:
            - pip
    - step:
        name: Dev deployment
        script:
          - ssh ubuntu@$IP_HOST "docker pull 273261189387.dkr.ecr.ap-southeast-1.amazonaws.com/wp-test:$BITBUCKET_BRANCH"
          - ssh ubuntu@$IP_HOST "cd /home/ubuntu/wp-dev && TAG=$BITBUCKET_BRANCH docker-compose up -d"