apiVersion: v1
kind: Service
metadata:
  name: wp-dev
  labels:
    environment: dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wp-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-dev
  labels:
    environment: dev
    app: wp-dev
spec:
  minReadySeconds: 15
  replicas: 1
  template:
    spec:
      containers:
      - image: 273261189387.dkr.ecr.ap-southeast-1.amazonaws.com/wp-test:dev
        name: wp-dev
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql-dev"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_PASSWORD
          value: ${DB_PASS}
        ports:
        - containerPort: 80